### PR TITLE
fix(policy): json_schema for conflict-resolution structured output (gpt-oss/Watsonx)

### LINKED ISSUE #411: [Bug]: Policy NL-trigger conflict resolution returns None on gpt-oss-120b (Watsonx) — policies never match
### What happened

On `openai/gpt-oss-120b` (IBM Watsonx), policy **NL-trigger conflict resolution silently fails** — natural-language-triggered policies never match.

`PolicyAgent._resolve_nl_trigger_conflicts` (`src/cuga/backend/cuga_graph/policy/agent.py:624`) calls `self.llm.with_structured_output(PolicyConflictResolution)` **without** a `method=` argument, so it defaults to function/tool-calling. `gpt-oss-120b` frequently returns **no tool call**, so the call returns `None`; the next line (`result.matched_policy_index`, agent.py:668) raises `AttributeError`, which is caught and falls back to "no match".

**Expected:** the matching policy is selected.
**Actual:** `policy_matched = False` for every NL-trigger policy.

One-line fix (matches the existing `OutputFormatter` at `enactment.py:924`; Watsonx enforces json_schema server-side):

```python
# policy/agent.py:624
structured_llm = self.llm.with_structured_output(PolicyConflictResolution, method="json_schema")
```

The rest of the agent graph is unaffected, since it routes through `BaseAgent.get_chain` (`response_format=json_schema`, which Watsonx enforces).

### How to reproduce

```bash
# Env: AGENT_SETTING_CONFIG=settings.watsonx.toml, MODEL_NAME=openai/gpt-oss-120b,
#      plus valid WATSONX_URL / WATSONX_APIKEY / WATSONX_PROJECT_ID
uv run pytest src/cuga/backend/cuga_graph/policy/tests/test_e2e_healthcare_family_claims.py::test_healthcare_family_claims_e2e_with_tools
```

Fails on `assert metadata.get("policy_matched")`; logs show the `AttributeError` below. Passes after the one-line fix.

### Environment

- OS: macOS (reproducible anywhere targeting Watsonx)
- CUGA: 0.2.28 (commit 6efa7f4b)
- Python: 3.12.7
- langchain-ibm: 1.0.7
- Model: `openai/gpt-oss-120b` on IBM Watsonx (`settings.watsonx.toml`)

### Logs, screenshots, or config

```
cuga.backend.cuga_graph.policy.agent:_resolve_nl_trigger_conflicts:668 -
❌ Error in LLM conflict resolution: 'NoneType' object has no attribute 'matched_policy_index'
AttributeError: 'NoneType' object has no attribute 'matched_policy_index'
→ Policy matched: False
```

### Checklist

- [x] I searched existing issues and this doesn't look like a duplicate

### PR DESCRIPTION
**Pull request by segevshlomovIBM**
## Bug fix

Fixes #411

### Summary
`PolicyAgent._resolve_nl_trigger_conflicts` called `with_structured_output(PolicyConflictResolution)` without `method=`, defaulting to function/tool-calling. On `openai/gpt-oss-120b` (Watsonx) the model often emits no tool call → returns `None` → `AttributeError` on `.matched_policy_index` → NL-trigger policies silently never match. Fix: pass `method="json_schema"` (enforced server-side by Watsonx; matches the existing OutputFormatter in `enactment.py`). The rest of the graph already uses `response_format=json_schema` via `BaseAgent.get_chain`, so it is unaffected.

### Testing
- [x] Verified fix locally; tests pass

**Checks performed — live on `openai/gpt-oss-120b` (IBM Watsonx):**
- Policy: the 2 failing conflict-resolution tests now pass; all 7 originally-failing policy tests pass in isolation after the fix.
- Full task-decomposition graph: `accurate_test` 3/3, `balanced_test` 3/3.
- AB / stability suite: 10/10 ×3 (100%).
- Mock unit tier (`run_tests.sh unit_tests`): ~535 passed / 0 failed.
- `ruff check` clean on the changed file.

### Related (follow-ups, not fixed here)
- #412 — policy e2e tests flaky with `RuntimeError: Event loop is closed` when run as a suite (test-harness async teardown; each passes in isolation).
- #413 — no live test coverage for the browser sub-graph & feature-flagged paths on gpt-oss/Watsonx.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved reliability of conflict resolution for natural-language triggers, reducing cases where responses could be misparsed or fail during processing.

### CODE REVIEW

File: src/cuga/backend/cuga_graph/policy/agent.py [hunk 1]
```diff
@@ -620,8 +620,12 @@ async def _resolve_nl_trigger_conflicts(
...
             logger.debug(f"    Number of policies in prompt: {len(policies_with_nl_triggers)}")
 
-            # Use structured output for reliable JSON parsing
-            structured_llm = self.llm.with_structured_output(PolicyConflictResolution)
+            # Use structured output for reliable JSON parsing.
+            # method="json_schema" (matching OutputFormatter in enactment.py) is enforced
+            # server-side by IBM Watsonx. The default (function_calling) returns None on
+            # gpt-oss-120b when it emits no tool call, which raised AttributeError below and
+            # silently dropped the policy match.
+            structured_llm = self.llm.with_structured_output(PolicyConflictResolution, method="json_schema")
```
Comment (haroldship) [inline src/cuga/backend/cuga_graph/policy/agent.py:628]: code change looks fine

**Review by haroldship — APPROVED** [review]
Approve with caveat: it seems like this code is not specific to watsonx. It would be prudent to test on other inference services.
